# Browser options: chrome, edge, firefox (please ignore firefox)
browser=chrome
# Base URL for your tests
baseUrl=https://automationexercise.com/
# Default timeout in seconds explicit and implicit
timeout=10

headless=true